name: client
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mqtt_client: 9.8.1
  shared_preferences: ^2.1.0
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  flutter_material_pickers: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  assets:
  - assets/config/.env
  - assets/images/tukorea.jpg
  - assets/images/child.jpg
  - assets/images/sky.png
 